### PR TITLE
Jadewallet grant application

### PR DESCRIPTION
**Pull request by daCapricorn**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

**Jadewallet** is a revolutionary self-custody solution that is built on foundation of the cutting-edge technologies including **MPC (multi-party computation)** and **TSS (threshold signature scheme)**.
The feature of **MPC-based Threshold Signature** offers users the complete control over their digital assets and the ability to achieve multi-signature with keyless cryptographic security.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
@daCapricorn Thanks for the submission. I have a couple of suggestions regarding your application:
1. We can only support Polkadot-specific deliverables. Therefore, your milestone 3 is out of scope for this grant program, though feel free to apply to other foundations for support.
2. The technical specifications are missing, starting with: 
```
MPC core:
Use Rust and Python to make a demo that works on a single pc.
```
You will need to provide much more detail of what you want to include in the core & in the demo.
The same applies to all the other points of your application.

3. Will users who are not part of Jadepool Hub/SaaS be able to use your app? If so, please describe how.
4. Could you describe a typical application flow for the end user, from start to end?

Thanks!

**Comment by daCapricorn** [comment]
@mmagician OK. We will update the application.

**Comment by daCapricorn** [comment]
> @daCapricorn Thanks for the submission. I have a couple of suggestions regarding your application:
> 
> 1. We can only support Polkadot-specific deliverables. Therefore, your milestone 3 is out of scope for this grant program, though feel free to apply to other foundations for support.
> 2. The technical specifications are missing, starting with:
> 
> ```
> MPC core:
> Use Rust and Python to make a demo that works on a single pc.
> ```
> 
> You will need to provide much more detail of what you want to include in the core & in the demo.
> The same applies to all the other points of your application.
> 
> 1. Will users who are not part of Jadepool Hub/SaaS be able to use your app? If so, please describe how.
> 2. Could you describe a typical application flow for the end user, from start to end?
> 
> Thanks!

@mmagician Please review the application again.

- A typical application flow description added.
- The answer to "Will users who are not part of Jadepool Hub/SaaS be able to use your app?" added in "Additional Information".
- Milestones are updated and more details added.

**Comment by mmagician** [comment]
@daCapricorn So as far as I understand, your wallet solution relies on a 3rd party centralised service (Jadepool SaaS/Hub?) for creation of the MPC wallet as well as for dispatching messages & transactions?

**Comment by daCapricorn** [comment]
> @daCapricorn So as far as I understand, your wallet solution relies on a 3rd party centralised service (Jadepool SaaS/Hub?) for creation of the MPC wallet as well as for dispatching messages & transactions?

Jadepool SaaS/Hub are not 3rd party, they are also our products. As centralized services for creation of the MPC wallet as well as for dispatching messages & transactions, etc. While Key shares are in users’ control.

**Comment by daCapricorn** [comment]
@mmagician

**Comment by mmagician** [comment]
@daCapricorn Unfortunately the Grant Committee decided against funding your proposal. The main reason for rejection is that your solution relies on a centralised service & doesn't present clear advantages to the ecosystem as a whole, but rather benefits users of your existing platform.

**Pull request closed without merging**
