### PR TITLE
Adding RFP for XCM library & tools

### PR DESCRIPTION
**Pull request by xlc**
XCM is an essential component to all the parachains. There are still a few missing pieces and it will be helpful if W3F is able grant some team is to complete this puzzle.

### CODE REVIEW

**Comment by alxs** [comment]
Just to clarify, do you plan to expand on this or shall we take it from here?

**Comment by xlc** [comment]
I don't plan to expand on this unless needs more clarification so you can take it from here.

**Review by mmagician — APPROVED** [review]
@xlc Thanks for the RFP.
@alxs I would say let's merge it for now, we can always expand the info later if needed - but in the meantime we might already get a team interested.

**Review by alxs — APPROVED** [review]
Fully agree. I'll leave it to @Noc2 to merge.

@xlc getting Treasury involved sounds like a good idea and I have the impression this would get more (immediate) exposure over there than here as an RFP.

**Comment by Noc2** [comment]
Sorry @xlc, I completely missed this PR. Thanks a lot and I fully agree we should merge it and potentially refine it/publish similar RFPs ourselves.

**Pull request merged**
