### PR TITLE
APPI: Auto-funded public p2p infrastructure

### PR DESCRIPTION
**Pull request by Swader**
RFP proposal for auto-funded public infrastructure for Kusama and Polkadot.

### CODE REVIEW

**Comment by Noc2** [comment]
In general, I like the idea and would definitely be interested in supporting something like this. However, I see two potential problems: First what are potential security issues of such a system? Couldn’t you trick the system very easily? A grand could potentially also try to address these issues and find solutions for it. And secondly, I think the success of infura is also based on laziness. It is always easier to just copy paste an endpoint.

**Comment by Swader** [comment]
Re 1) If you submit invalid data and enter the pool as a valid node, you gain nothing - you spend computing resources by spoofing this info. If your "node" is then picked during the LB's random selection, the request will hit your dead end and your node will be reported as unresponsive or invalid, thus becoming blacklisted for future requests. Additionally, the LB should periodically ping nodes for information like latest block etc, to make sure they're still valid and around and ready to serve. Failing this liveness check can also blacklist a node. I don't think this is much of an issue.

Re 2) Indeed, that's why this should be developed early so this endpoint can be used as easily as plugging in an infura-like endpoint. We had this for a while with Avado and it worked well, but this is now decommissioned.

**Comment by Noc2** [comment]
Regarding security issues, I was more thinking about the pool itself, which needs to be trusted if I understand it correctly. 
Btw. for the append-only database you could use something like [orbit db](https://github.com/orbitdb/orbit-db), to make it more decentralized. Anyway, I’m happy to merge the PR, unless you have any outstanding issues or want to change something.

**Comment by Swader** [comment]
Ah, yes, the idea is indeed to have a trusted ops owner. The power this provides us with is incentive for random people to spin up good pools and market the hell out of them, as well as set them up properly and keep an eye on them. So while each pool won't necessarily be decentralized, the infrastructure is - the alternative pools and the competition will take care of availability and resilience.

No issues on my end, please merge!

**Comment by Noc2** [comment]
@Swader Btw. Do you know of any specific teams, which could be interested in working on something like this?

**Comment by Swader** [comment]
I do not right now, but I'll actively try to seek them out

**Pull request merged**
