### PR TITLE
polkaj android support proposal

### PR DESCRIPTION
**Pull request by nschwermann**
# Grant Application

This application is (select one):

- [x] Speculative (use this by default)
- [ ] an RFP response

This application is (select one):

- [x] Public (fully)
- [ ] Public with private finances

## Abstract

The PolkaJ java client is built using Java 11 and 9 APIs and native x86 code which can not run on Android.
This project proposal will make the necessary changes to support the Android platform as well as provide examples.

## Checklist

- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [ ] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Nathan, 
thanks for your application! Could you please fill out the [Google form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) as well? The README is not super clear on that, but it's actually required in the General Grants program.

**Comment by semuelle** [comment]
Will you merge these changes with polkaJ, or are you planning to maintain a separate repository? 

I just checked, and the price is currently ~31.7k USD. If the price is below 30k, you can apply through the [Open Grants program](https://github.com/w3f/Open-Grants-Program/), which is faster and usually easier. In your case, I would highly recommend it. The process is almost the same.

**Comment by nschwermann** [comment]
Hello yes this would merge into polkaJ. Should I change the proposal to
stable coin? It is meant to be 30k.

**Comment by semuelle** [comment]
Cool. 

No, the Google form is not required for an open grant. Just head over to that repo and follow the instructions there. You can reuse most of what you submitted here. It'll be denominated in USD and paid out in BTC or DAI.

I'll close this one then. See you on the other side.

**Comment by nschwermann** [comment]
Hey @semuelle I opened an open grant PR as you suggested last week. I've seen several PR come in after mine that have received comments, change requests and reviews from the team but no response or feed back on mine. I am wondering if this is normal, looking through the PR history I don't think I've seen any PR take so long to be acknowledged. Is there someone I should reach out to or just sit tight?
Thanks.

**Pull request closed without merging**
