### PR TITLE
Open Square Network - BlockChain Based Crowdsourcing and Reputation Platform

### PR DESCRIPTION
**Pull request by wliyongfeng**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

Open Square Network is a blockchain based crowdsourcing and reputation platform. It will be implemented as a para-chain
of Polkadot. We aim to attract thousands of middle and small sized enterprises and millions of developers in China for the first phase. This platform is a trial to evolve the human resource market. First phase features include:
- Bounty funders can fund a bounty, while hunters can apply it.
- Funders can get mining power by successful collaboration with hunters.
- Reputation of both funders and hunters will be calculated based on the finished bounty and remarks.
- Aim to maintain relatively long collaboration between bounty funders and hunters.
- Platform fairness and transparency will be provided by on-chain governance. 

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by siman** [comment]
This looks interesting

**Comment by wliyongfeng** [comment]
> This looks interesting

Thanks for your interest. 
I think OpenSquare have some common target with subsocial.network for reputation building, while we try to achieve this by tracking the collaboration data.

**Comment by siman** [comment]
@wliyongfeng would you like to have a chat about the way to build a reputation model on Substrate?

**Comment by wliyongfeng** [comment]
> @wliyongfeng would you like to have a chat about the way to build a reputation model on Substrate?
> We already built one version, but I want to improve it.

Sure about it. Please add my telegram contact https://t.me/wliyongfeng .

**Pull request merged**
