### PR TITLE
PolkaJ support

### PR DESCRIPTION
**Pull request by splix**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract

We have developed the [Java client library for Polkadot](https://github.com/emeraldpay/polkaj), which was done with the help from another Grant by W3F. At this moment, the library covers most of the critical features required to access Polkadot from a JVM-based app.

We'd like to continue the work on the project, as well as do maintenance and work with the community of Java developers.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [ ] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [ ] Abstract (above) is succinct and complete.
- [ ] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [ ] The application includes a project description.
- [ ] The application includes all names of team members.
- [ ] The application includes a description of the team's experience.
- [ ] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [ ] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [ ] The "Development Roadmap" section in the application has an estimate of funds required.
- [ ] The "Development Roadmap" section gives an indication of the team's long term plans.
- [ ] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
@splix Thanks for another application.

We do not usually support library maintenance without specific goals.

For example:

> implement the missing API

You could list the specific ones that are missing & that you are willing to implement in a milestone.

> bug fixes

Are there specific bugs that have been reported?


That said - ideally, other teams using your library would be making contributions to improve it. Do you know if there's been much interest in your work from the community or perhaps projects that have utilised it?

Another option to get support would be to apply for the [treasury funding](https://wiki.polkadot.network/docs/en/learn-treasury#creating-a-treasury-proposal).

Let me know your thoughts.

**Comment by splix** [comment]
Hi @mmagician 

Thank you for your reply. You're right that some specific and large enough work should be submitted as individual proposals, with milestones, etc. I may consider making it for large parts of work. But this proposal talks explicitly about support and maintenance, which is unmeasurable. 

You mentioned that you want "_other teams [...] be making contributions_".  And that's exactly the purpose of the proposal. I mean, every open-source project wants other people to contribute, but unfortunately, it doesn't just happen in the real world. The only way to make it happen is continuous communication with that community of developers, answering their questions, fixing mentioned bugs and usability problems, writing docs and tutorials, etc. 

And that's what I propose here. Since I know what this community of developers may need, know how to learn from them what the library lacks, as well as how to build some space where those developers may have easier onboarding in using Polakdot from JVM.  

The goal is to make the community of Java (Kotlin, Scala, Clojure, etc.) developers that would use the library to build for Polkadot, and ideally contribute back. It doesn't happen by itself. And it's impossible to measure that kind of work; it's just a lot of time invested with a possible return as contributions from others.

Fixing bugs and making improvements is not really the main part. However, I think that the library still has a fraction of what it should provide. And it can be significantly improved as a part of the proposed work.

PS You can see the issues here btw: https://github.com/emeraldpay/polkaj/issues

**Comment by mmagician** [comment]
@splix I do share your opinion that it would be difficult to quantify the work needed for community bootstrapping and support. And yes, I realise that my thinking is somewhat idealistic regarding the community working on the project organically. 

That said, such a commitment from our side would be a blind move, as the community engagement is hard to predict on a weekly/monthly basis and we may end up paying for support when none is actually needed. While at a future point in time we might consider an ongoing service-type agreement to support the Java community & lib development within Polkadot, I believe the Java sub-community hasn't quite gained enough traction yet, from looking at your repo's issues/PRs.

The current options I see are the following:
- Apply for another grant for concrete development ideas, specifying deliverables & milestones like before. If these are one-off, small developments (or even a few bundled together), then applying via the Open Grants Program would be the best option, as we could iterate much quicker & don't need the approval of the Grants Committee.
- Make a proposal for a community-building activity and apply for treasury funding (Polkadot or Kusama). As an example, you could make a series of videos/live streams, write a sample app or maybe even propose to organise a Hackathon for Java builders for Substrate.

I hope that helps

**Comment by splix** [comment]
Hi @mmagician,

I understand your concerns and why you suggest doing only parts of the proposed work as individual grants. But I don't see how it's possible. I mean, even for the initial grant, it didn't work well, and I don't think it can be continued that way at this moment. Because the lib needs support/maintenance work, you cannot move forward with new development without someone dedicated to it.

I'm not sure if you made any estimations, but there's already much work even with current issues. It would take a couple of weeks just to work on them. And launching a good website with docs is a couple of more weeks. Plus other things, it easily stacks up. And the amount of new work only increases over time. So it's not really that simple as it looks.

Someone needs to do that job. You're right that there is not so much community activity right now, but it cannot magically happen without someone starting to work on it. Otherwise, it will be just a dead project. 

I think it's important to make the lib alive and attract Java developers (i.e., developers of most business and android apps) into the Polkadot ecosystem. And if someone would want to hire people to do that job of supporting the java lib, it would cost a few times more (and the biggest challenge would actually find whom to hire). In this proposal, there is a unique opportunity to make it for less than half the price.

**Comment by mmagician** [comment]
@splix I also understand your concerns and agree with most of the points you raised. The solution you propose is not necessarily bad - it's just difficult to ensure correct execution of such an agreement & quantify progress.

Let's do the following: I will include your proposal in the next Grant Committee meeting (in two weeks) & we will continue our conversation depending on the outcome of the decision - I'll keep you informed. In the meantime, may I suggest that you better define the deliverables that *can* be quantified, such as `Cover/implement the missing APIs`? This will enable the committee members to better assess the scope of that part of the proposal. 

I hope that works with you.

**Comment by mmagician** [comment]
@splix Thank you for the patience.
As promised, I brought up the topic of your proposal with the Grants Committee. Unfortunately, the decision to reject the proposal in its current state was unanimous. The main reason for this was a high cost for an unspecified amount of work.

That said, we agreed that given the high quality of your previous deliveries, we would like to support the polkaj project in some form or shape. The options for going forward are the following:
* Specify concrete milestones and apply via [Open Grants Program](https://github.com/w3f/Open-Grants-Program) for smaller (sequential?) grants
* Work on a project/application that utilises polkaj library

I'm closing this PR for now, but please let me know if you are interested in any of the above options.

**Pull request closed without merging**
