### PR TITLE
Add Polkaswap

### PR DESCRIPTION
**Pull request by pgolovkin**
Add Polkaswap DEX

## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

Polkaswap is a non custodial cross chain AMM DEX designed uniquely for the Polkadot and Kusama ecosystems and hosted on the SORA 2.0 network

## Checklist
- [ ] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [ ] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [ ] Abstract (above) is succinct and complete.
- [ ] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [ ] The application includes a project description.
- [ ] The application includes all names of team members.
- [ ] The application includes a description of the team's experience.
- [ ] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [ ] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [ ] The "Development Roadmap" section in the application has an estimate of funds required.
- [ ] The "Development Roadmap" section gives an indication of the team's long term plans.
- [ ] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
Instead of https://polkaswap.io/, could you put the url of the repo where your code is hosted please?

**Comment by pgolovkin** [comment]
@mmagician I've added a link to the public github repo.

**Comment by zilenka** [comment]
@Noc2  Hi! when is this PR going to be merged?

**Comment by mmagician** [comment]
It seems that the link points to the front-end, which is not immediately usable.
Do you perhaps have links to the backend implementation, or perhaps are planning to add some instructions to the frontend repo on how to use it?

**Comment by pgolovkin** [comment]
@mmagician currently we have a testnet launched. We're going to publish our sources right before the mainnet launch. You can find Polkaswap.io tesnet [here](https://test.polkaswap.io/exchange/swap). 
Can you merge this PR with existing source link?

**Comment by zilenka** [comment]
@Noc2  @mmagician  currently we have a testnet launched. We're going to publish our sources right before the mainnet launch. You can find Polkaswap.io https://test.polkaswap.io/. Can you merge this PR with existing source link?

**Comment by mmagician** [comment]
Is there an emergency to get this merged?
As soon as your repo is made public we can include it in our stack.

**Comment by mmagician** [comment]
Closing due to inactivity.

**Pull request closed without merging**
