### PR TITLE
Threshold BLS Randomness Beacon for Substrate

### PR DESCRIPTION
**Pull request by AdamGagol**
## Grant Application

This application is Speculative

###

This application is Public with private finances

### Abstract

The goal of the project is to construct a Substrate pallet implementing a randomness beacon based on the well-known idea of extracting randomness from threshold signatures, specifically, using the BLS signature scheme. 

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by burdges** [comment]
I'll glance over the linked articles eventually :) but super busy right now.  We've ongoing discussions with about a DKG grant proposal, which maybe we should involve you in, and must end up ported to non-pairing based curves too.  It's languishing because I'm too busy with higher priority work right now.

I should clarify that pallet_randomness_collective_flip exists for tests, and should never be used in production.  

We export respectable "fast" randomness from BABE right now and Sassafras shall continue or improve upon this.  Yes, one should ideally do a security proof that BABE's bias suffices for their their specific usage.  Ain't fun if you must wait two epochs for randomness, but doing this provides the strongest option.  It's what we do in-house, but it does not fit all use cases true.  We do however think BABE's randomness fits many low stakes use cases that require fast randomness, especially most games.

In BABE, adversaries have foreknowledge about only their own blocks' randomness, hence the waiting.  Adversaries can bias this randomness only by (a) electing not to make their own block, or (b) not building upon another block with a transaction they dislike.  We cannot address either with any on-chain randomness scheme really, so..

We're discussing an off-chain randomness schemes in which parachain collators gossip threshold BLS shares in time for their next block, perhaps even assigning the block producer using this VRF.  

Aside from all the complexities in such protocols, there are liveness concerns that make the less complex ones unsuitable for parachains, and parathreads maybe face worse concerns, so..

I'd expect such protocols should structure nodes participants into groups, perhaps according to protocol specific metadata, so that they can use [RandHeard](https://bford.info/pub/dec/random.pdf).  I'd expect the [drand](https://github.com/drand/drand) implementation of RandHerd in Go by the DEDIS group at EPFL and CloudFlare developed quite well https://www.cloudflare.com/leagueofentropy/ 

We obviously need any push this direction to first understand how best to aligns with those efforts, but moreover the question here might really be:  Can drand be integrated with a parachain sensibly?

**Comment by DamianStraszak** [comment]
Thanks for taking your time to look at this despite being busy!

In the proposal we avoided including technicalities and kept the description at a rather high-level, but in fact we have had a number of discussions and thought quite a bit about integrating threshold BLS randomness with blockchains. Let us elaborate here a little more on these ideas and technicalities.


First of all let us clarify that even though there exist numerous DKG  protocols ([Gennaro et al.](https://link.springer.com/article/10.1007/s00145-006-0347-3), [Cachin et al.](https://dl.acm.org/doi/10.1145/586110.586124), [Kate et al.](https://eprint.iacr.org/2012/377), [our work](https://arxiv.org/abs/1908.05156), [Kokoris et al.](https://eprint.iacr.org/2019/1015), etc.) and numerous implementations ([drand](https://github.com/drand/drand), [dfinity](https://github.com/dfinity-side-projects/random-beacon), [Keep](https://docs.keep.network/random-beacon/)) all of these are **very** similar to each other, and from a (sufficiently) high perspective are merely variants of the [Pedersen DKG protocol](https://link.springer.com/chapter/10.1007%2F3-540-46416-6_47). Thus in particular, familiarity with Pedersen’s protocol gives a solid basis for understanding all the remaining ones. There are essentially two reasons why the research on DKG did not stop right after Pedersen’s work:

- It turns out that Pedersen’s protocol does not guarantee a uniform distribution of keys and thus might be considered unsafe. This issue was resolved quite early on by [Gennaro et al.](https://link.springer.com/chapter/10.1007%2F3-540-36563-X_26) who showed (translating to our usecase) that randomness generated from such keys is anyway safe and unpredictable.

- Pedersen’s protocol works under a quite unrealistic model of the network and adversary. Specifically it assumes full synchronicity -- every message transmitted by an honest node reaches its destination before a prespecified deadline “delta”.

As it has been extensively argued in the literature, synchronicity is not a valid assumption for today’s internet, especially in the context of blockchain, where the adversary might have some impact (using DDoS attacks) on message arrival. Thus the more recent protocols focus on adjusting Pedersen’s to stricter models: partial synchrony ([Kate et al.](https://eprint.iacr.org/2012/377)) and full asynchrony  ([our work](https://arxiv.org/abs/1908.05156), [Kokoris et al.](https://eprint.iacr.org/2019/1015)). Of course, there is nothing for free -- the cost of adapting the protocol to a stricter model makes it generally much more complex and requires significantly more bandwidth. 

An important realization here is that the reason why Pedersen’s is not easily adaptable to stricter models is that it requires the nodes to perform some form of reliable broadcast and reach consensus. Both these primitives become increasingly more complex when going towards asynchrony. However, given access to a blockchain -- these two are not hard anymore! If the nodes performing DKG can use a blockchain as a “broadcast channel” that can order the broadcast messages, then this task becomes significantly simpler, as consensus is solved for us. This has been already observed in [Schindler et al.](https://eprint.iacr.org/2019/985) , who designed a DKG protocol that can work as an Ethereum smart contract.

We believe that such a way of implementing Pedersen’s DKG is a perfect fit for Substrate, simply because the consensus mechanism is a an independent module that is present anyway and it gives a lot of benefit to use it for the purpose of a simple, yet robust DKG. In particular, such a blockchain-powered DKG is resistant to periods of network asynchrony (DDoS attacks) that would in contrast harm regular synchronous implementations of DKG. An especially simple and asynchronous version of DKG can be then easily established for a thresholds <=N/3+1. 


**Regarding pairing vs non-pairing curves:** the DKG protocol (and the randomness generation protocol) does not require the curve to be pairing-friendly. In fact the paper of [Cachin et al.](https://link.springer.com/article/10.1007/s00145-005-0318-0) where the use of threshold signatures as a source of randomness has been initially proposed was published even before any pairing-friendly curve was known. At this point they have used the order-q multiplicative subgroup of (Z_p,*) for p=2q+1, where both p, q are primes. Essentially, the only requirement from such a group is that it has prime order and the Decisional Diffie-Hellman problem is hard in G. This then allows to construct suitable succinct non-interactive zero knowledge proofs for relations such as equality of discrete logs.

In the context of randomness generation, the particular interest in BLS (or rather in pairing-friendly curves) comes from the fact that the inclusion/transmission of these specific zero-knowledge proofs is no more necessary, as a pairing check can confirm equality of discrete logs without any additional data. Consequently, making these protocols slightly more bandwidth-efficient. When it then comes to implementation of, say, DKG, one can easily make it generic, so that when instantiating it with a particular group, one only needs to provide methods for creating certain NIZKPs (nothing in case of pairing EC) and for verifying these NIZKPs (a pairing check in case of pairing EC). 



**Regarding integration of drand:** there are two ways we can imagine integrating drand into Polkadot:

- as an external service -- to relay and use the randomness created by the main drand network (https://www.cloudflare.com/leagueofentropy/, thus nodes external to Polkadot).

- to use drand’s source code to build a randomness beacon inside of Polkadot.

Option 1) requires perhaps far less effort to implement, yet introduces several limitations, most importantly the League of Entropy randomness source produces randomness every 60 seconds, thus limiting the blockrate of each chain that intends to use this randomness. Such a chain would in particular need to wait with block creation until the LoE’s randomness is ready. At the very least, liveness of such a chain relies then on livenes of LoE.

Option 2) requires more work, and in case the implementation is expected to be in Rust, it would be more or less equivalent to rewriting DKG from scratch. Furthermore, as we argued in the lengthy introduction on DKG, we believe that (as we propose) an implementation that is closely coupled with the underlying blockchain is more robust than what one would obtain by adapting the drand code (which implements the basic version of Pedersen’s protocol). It is also worth noting that simply adapting drand would result in a protocol that is run “off chain” and thus would perhaps not be perfectly compatible with Substrate’s architecture and vision. In contrast, the variant of DKG we propose, can be naturally encapsulated as a Substrate pallet.

**Comment by vshvsh** [comment]
FYI, check out [our work](https://github.com/corestario/tendermint) on Tendermint with built-in BLS random beacon. It's not production-ready, but there are a few nice ideas you can borrow about how we conduct DKG. Namely, we try for offchain DKG first and then follow with attributable slashable but expensive onchain one if case the former fails. It works quite well in tests for under 30 nodes but for more than that DKG becomes a little bit unreliable.

**Comment by burdges** [comment]
At some level games need to produce values themselves.  Is the original proposal hear meaning to generate a new value every block?

**Comment by DamianStraszak** [comment]
@vshvsh: thanks for bringing this to our attention! We are taking a look.

@EdwardAThomson: I would imagine that from a viewpoint of a blockchain game developer, a reasonable assumption would be that “At every block there is a new fresh random seed available”. In particular, not having this assumption might:
- either make his/her job harder -- need to add some logic that waits for fresh randomness if there is none yet,
- or can even make his/her code unsafe -- because clearly reusing “old” randomness might cause problems.

Now, whether 1 block is 1 second, 10 seconds, or even 10 minutes, it depends on the blockchain (also might change in the future). So we believe it is good to have a randomness beacon run within the same blockchain, at the same pace (that is capable of producing randomness even every single block), instead of importing randomness from external sources.

@burdges: In the solution we propose there are essentially two options (we can make it configurable)

1. Run the randomness beacon completely independently from the blockchain -- then unfortunately there is no way to guarantee how frequently fresh randomness will be delivered, yet this option does not require to change block creation rules.
2. Add a rule to block creation that the fresh randomness is available every K blocks (one can make K=1 or higher upon need). In other words, force the block author to wait till the fresh randomness is ready and make him include it.

In the second option you guarantee that randomness is generated every K blocks. The question though becomes whether this new constraint (waiting for randomness) will not slow down the blockchain. We would argue that unless the block-time is subsecond, it should not slow down things. That’s because generating fresh randomness essentially boils down to generating and broadcasting 1 constant-size piece of data per committee member (its signature share) and then collecting these pieces and combining them by, say, the block author. 

To give you some numbers, our randomness beacon written in Go, for committee size N=128 could produce randomness in <0.5 sec (and in fact this was not even the bottleneck). I don’t know how would this time translate to the Substrate architecture, as our beacon essentially used 1-to-N broadcast to disseminate signature shares, and not gossip. Anyway, I would expect this to be pretty fast.

**Comment by burdges** [comment]
It's worth clarifying that C code is generally not useful to us.  ref. https://github.com/paritytech/substrate/issues/7583

**Pull request merged**
