### PR TITLE
integrate AssemblyScript to write smart contract

### PR DESCRIPTION
**Pull request by synote**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract

**Subscript** is a smart contract language written in AssemblyScript for substrate based chain. We will provide essential substrate api and builtin tools to support contract development.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
@synote Thanks for the application.
I have a few comments:
1. Could you expand on `integration with substrate node` part please? How do you envision such a tool would work?
2. For each milestone, please include a deliverable that covers:
- unit tests for that milestone's scope
- a full test (integration) that demonstrates how the added smart contract functionality actually works, when deployed on a local substrate node

Thanks!

**Comment by synote** [comment]
To clarify milestone4:
`integration with substrate node` : we will provide some substrate cli options to deploy and call the `Subscript` compiled contract with substate node.

We may apply for open grant programe for our milestone 1 to start our assemblyscript project. The first milestone will implement all the basic contract runtime api and we will show the assemblyscript sdk package.

**Comment by Stefie** [comment]
In addition to my comment in Open Grants Proposal, there's another thing I notice. It will make sense to move the implementation of the SCALE codec from Milestone 3 to Milestone 1. 
All Types and data structures used for in Substrate ad Polkadot can (and must) be described as one of the types implemented in SCALE, so it does not make sense to implement core types like `AccountId`, `Balance`, `Hash`, `Block` without using Limechains [as-scale-codec](https://github.com/LimeChain/as-scale-codec).

**Comment by synote** [comment]
LimeChain's as-scale-codec can speed up our development. We may import `as-scale-codec` directly in our implementation.

**Comment by synote** [comment]
w3f/Open-Grants-Program#61

**Comment by synote** [comment]
w3f/Open-Grants-Program#61

**Comment by Noc2** [comment]
Open grant signed: https://github.com/w3f/Open-Grants-Program/pull/61

**Pull request closed without merging**
