### PR TITLE
Subauction: NFT marketplace

### PR DESCRIPTION
**Pull request by repetny**
# Grant Application

This application is:

- [x] speculative (use this by default).
- [ ] an RFP response.

This application is:

- [x] fully public.
- [ ] public with private finances.

## Abstract

> Provide a brief description of your project here summarising key points (1-2 paragraphs).

NFT marketplace with auction system that can be able easily integrated into other NFT solution standards developed on Polkadot.
Our end result is a feature-specific pallet that could be plugged into other blockchain applications and an NFT auction marketplace application with DAO curated exclusive content. 

> If your application is a follow-up to a previous one, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
>
> The details should be in the application document that is being added to the repository via this pull request.

## Checklist

- [x] The [README](../README.md) has been read and understood.
- [x] The abstract above is succinct and complete.
- [x] The [application form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be filled out accurately. Note that you will require the URL of this pull request.

The application:

- [x] is being added to the correct directory, either [`rfp-responses`](https://github.com/w3f/General-Grants-Program/tree/master/grants/rfp-responses) or  [`speculative`](https://github.com/w3f/General-Grants-Program/tree/master/grants/speculative).
- [x] includes the names of all team members.
- [x] contains a summary of the team's experience.
- [x] links to the GitHub and LinkedIn profiles of all team members that have one.
- [x] includes a comprehensive timeline of development.
- [x] includes an estimate of the funds required (optional).
- [x] provides an indication of the team's long term plans.

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for your application. Looks good at first sight, but as usual we would highly recommend applying for an initial grant of up to $30k through Open Grants instead, which would be faster and likelier to be accepted. Let me know if this is something you would consider.

Other than that, have you been in communication with the wider community? E.g. in the context of the [NFT strategy for Kusama](https://kusama.polkassembly.io/post/303) or in the current discussion in [Polkadot Direction](https://app.element.io/#/room/#polkadot-direction:matrix.parity.io).

**Comment by pmensik** [comment]
Hey @alxs, yep, we've had a lot of discussions with other NFT projects that are going to be released as a Polkadot parachain since we signed up for the Encode Hackathon where the basis of the auction system was developed. We were also in touch with Dan Forbes responsible for delivering the Kusama gallery (he helped us with the hackathon), I frequently talk with @yangwao about the future of NFTs and we are part of the ecosystem (as Polkadotters) already so we have sparked some discussions within our community as well. 

It's kinda hard to reduce the grant up to $30k since it's pretty clear that development will take 3 people for around 3 months at least. At the same time, it's difficult to split up the work between multiple grants doesn't really make sense to develop the frontend (and our goal is to have really superb UI & UX) and backend separately, together with integration to existing NFT projects.

**Comment by alxs** [comment]
Sounds good. Just a few remarks to ensure a smooth sailing during the review of your application:
- The definition/explanation for Auction Type Generalisation is missing.
- The link to Governance & Content Curation in the milestone is broken.
- Could you add more technical details i.e.
  - for M0, 1 and 3, will you add all of this to the ORML NFT pallet or how do you plan to implement it?
  - Could you link to a specification/reference/pseudocode for the auction types? What governance and content curation mechanisms do you plan to implement?
- Regarding M2, I think in general we don't fund mock-ups and design work but @Noc2 will be able to confirm or correct me. If you could provide a first mock-up as part of your application that would be ideal.
- Are you aware that one FTE represents one month of full-time work? I.e. if you plan to implement M1 within 1-2 weeks and you expect the workload to amount to 2.5 FTEs, that would mean 5-10 people would need to be working on it.
- The price and FTEs seem a bit high to me in general.

As for an ETA, your timing is quite fortunate with regard to upcoming Committee&Council meetings and if your application is accepted without further changes you should be able to start in about 2 weeks.

**Comment by repetny** [comment]
Thanks for a review @alxs and all stated makes sense. 

We're going to update the application per your suggestions and FTE were calculated as full time working people, not exactly as equivalent of full time working for 1 month - in that case I'm going to update it, effectively dividing the FTE number by 2 in case of 1-2 weeks timeline.

Thanks for the heads up about timing, sounds promising!

**Comment by alxs** [comment]
Huh, I think I actually got that wrong. Don't know where I got the notion from but yours seems to be the regular interpretation. Please leave them as they were, and sorry for the confusion :)

**Comment by repetny** [comment]
@alxs we updated the application. If mockups/design work won't fit in to get covered by grant, we will work around it with own resources and remove it from milestones and funding then.

**Comment by alxs** [comment]
Thanks a lot. I have my doubts this will be accepted without changes by the committee and would really encourage you to put some effort into doing more research and to expand on technical details of the entire application. See my previous comment for suggestions.

I.e.
> As the long-term goal is to support as many different types of [insert here] as possible, the application has to be flexible enough to provide an easy interface to plug them in. This will be made possible by making the solution more robust with its architecture overhaul. In order to achieve genericity, we want to create a higher level of abstraction and provide more suitable data structures.

This whole paragraph is so vague I only need to replace one word to make it work for anything I want. I personally like `blockchains`, `NFTs`, `keyboards` or `floppy disks`. Meaning it contains no valuable information.

I hope you see what I mean.

**Comment by green-jay** [comment]
Hi @alxs, first of all, thanks for all the feedback, highly appreciated!

I love floppy disks too, especially ever since the Commodore64 era!

I got your point and I do admit I was not entirely sure about the level of technical details to go into, In practice the generic paragraph means that we need to:
- redefine traits and add more of them (these are interfaces to handle various types of auctions), current solution has only 1
- add handlers/methods for events that operate these auctions
- add structs to keep on-chain data about these auctions
- and in the longer run (likely not within M0) create more connectors for NFTs, currently we have only ORML but there are more solutions on the market and we want to integrate these into our solution by modification of these pallets to be compatible
- and ...

Would this be a better level of details or there are still some pieces of the puzzle missing? I am not sure we want to bound our proposal to deeper levels of technical details to keep our hands free. Or would you expect things such as pallet design or architectural model? In that case could you recommend proposal with amount of tech. details you like?

**Comment by alxs** [comment]
Hi @green-jay. I only started playing around with computers when a floppy disk bay was still in every computer but floppy disks themselves had all but disappeared, so I can't speak from experience, but I agree they're a nifty piece of historic hardware.

That's exactly the level of detail that we would like to see. For the set of features that you shared for M0, that allows me to say that my impression is that it should be possible to deliver those together with M1 for a slight increase in price.

Considering that we cannot fund wireframing + mock-ups and that you would ideally provide those to apply for the UI work (consider this a "level of detail" requirement for such work), that leaves the price of the rest of the milestones somewhere at around $30k, so I would still strongly encourage you to apply via Open Grants for the backend first, do the UI design work in parallel and then apply for that.

Another option would be to still apply for the [PolkaTax](https://github.com/w3f/Open-Grants-Program/pull/333) grant first.

Your concerns regarding the level of detail provided and restrictions this puts on implementation freedom on your side are valid, but that's exactly the reason we ask for these: if we don't, teams can deliver a minimal implementation that meets a vague specification and it is hard for us to justify requesting changes. So please provide as many details as possible; where you're unsure of which route you'll take, you can still highlight this fact.

Lastly, considering it will likely take you some time to add the requested details to your application and that it would have to be handed in tomorrow for it to be discussed in the upcoming Committee meeting such as to have a chance to be accepted as per my initial estimate, it's likely you'd have to wait until the next Council meeting in May to get started. So that's another reason to go for Open Grants.

**Comment by green-jay** [comment]
This makes a lot of sense @alxs. As we are in for the long run and we still do have some of the deeper technical questions unresolved or undocumented, we will start off with Open Grants Program and after that we will be working on resolving those until May when we are ready for a follow-up application with greater details.

Would you have any idea about Open Grants approval dates?

**Comment by alxs** [comment]
Sounds good and makes sense. The application process for the Open Grants Program can take from under one day to a couple of weeks and largely depends on the level of technical details of the application and how well you can address the evaluators' feedback. See the [application review process](https://github.com/w3f/Open-Grants-Program#pencil-process) for details, currently 3 approvals are needed.

**Comment by semuelle** [comment]
Closing this one in favor of the [Open Grants application](https://github.com/w3f/Open-Grants-Program/pull/351).

**Pull request closed without merging**
