### PR TITLE
Polkadot KMS grant application

### PR DESCRIPTION
**Pull request by Lbird**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

### 

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract

In this project, we will design and implement a remote signer module within Substrate, and also a dedicated key management server to be used with the remote signer module.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by burdges** [comment]
Is this the team who discussed this in substrate repo issues?

**Comment by Lbird** [comment]
> Is this the team who discussed this in substrate repo issues?

I think not. I don't know the issue you mentioned. Can you give a reference to the issue?

**Comment by Lbird** [comment]
It seems to be our mistake, did not find the issue when we started discussing this project. I've just glimpsed the issue, and found that the goal almost overlaps. However, our long-term goal is to implement a KMS which can be used with Substrate. After paritytech/substrate#4689 is resolved with a concrete implementation or after remote signing protocol is fixed, we may be able to implement our own version of a signing server. I think it is still a meaningful project since it enriches the ecosystem.

Anyway, what is your suggestion? Just withdraw this PR and wait and monitor the issue 4689 until we apply for another grant? Or revise this PR now with a new revised goal?

**Comment by hskang9** [comment]
Even though the proposal may not be able to work on remote signer, I think this has value in that it can enable existing enterprise organizations to provide secure recovery service [here](https://github.com/paritytech/substrate/blob/3c80891f4120903b75d75a54c6a040ecf6724865/frame/recovery/src/lib.rs).

**Pull request closed without merging**
