### PR TITLE
Subsocial. Chapter 2

### PR DESCRIPTION
**Pull request by siman**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

Subsocial is a set of Substrate pallets with web UI that allows anyone to launch their own decentralized censorship-resistant social network aka community. Every community can be a separate Substrate chain and connect with other communities via a Polkadot-based relay chain.

You can think of this as decentralized versions of Reddit, Stack Exchange or Medium, where subreddits or communities of Stack Exchange or blogs on Medium run on their own chain. At the same time, users of these decentralized communities should be able to share their reputation or transfer coins and other values from one community to another via Polkadot relay chain.

To learn more about Subsocial, please visit [Subsocial Network](http://subsocial.network).

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by siman** [comment]
> is it possible to deliver simple MVP alone?

Hey @TomaszWaszczyk what do you mean by "simple MVP alone"?

**Comment by siman** [comment]
There is a WIP version of Subsocial deployed here:
http://dapp.subsocial.network

It includes half of the features from the first milestone of this grant application on both Substrate runtime and web UI sides. 

This month we are planning to launch the next version of Subsocial blockchain + updated web UI with re-implemented comments and even more.

**Comment by TomaszWaszczyk** [comment]
Mea culpa. I am asking about your experience. How many people are needed to be able to deliver SubSocial as working ready to validation by the market?

"simple MVP alone" I have written, yes, not concrete language. I asked because I am thinking about eg. decentralized meetup.com or platform similar to Tinder and thinking how many (and with which skills) I need to deliver it. And I saw your presentation and saw that you have experience with developing on Substrate (me not, nothing production ready as far as me is concerned).

**Comment by siman** [comment]
@TomaszWaszczyk got it. I think that **at least** you should have two developers on your team. One guy is a Rust developer and he/she should learn (or already know Substrate), and another one should be a front-end developer.

If you are going to create a web-app with React.js then it will be much easier for you because you could reuse some (or all) out UI components. But I believe that you can build UI with Vue.js - because there is a KodaDot lib that provides Vue.js components for Substrate; and plus we have a [JS packages](https://github.com/dappforce/dappforce-subsocial-js) that make it easy to work with Subsocial blockchain and we use them on our UI.

Also, keep you would need a third developer if you want to develop a mobile app(s) along with the development of Rust and web-app parts.

About how long it could take to develop meetup.com clone - everything depends on how many custom features do you want to add on top of what is already included in Subsocial. But we try to find and implement the features that are common across different social networks. This means that the more features Subsocial has - the easier it will be to create different custom social networks on top of it.

**Comment by TomaszWaszczyk** [comment]
Thanks!! I just was curious your experiences. Yes, exactly, you said that writing components is good idea. I think similar. In traditional programming some time ago I created component library: https://github.com/thirdwave-network/components-library do you think whether is good idea to create component library for Substrate applications? Does it make sense?

I ask because I look for idea for smaller grant where I will be able to learn new things but also deliver it and add real value - just implement useful tool to the community.

**Comment by siman** [comment]
> create component library for Substrate applications

What kind of components are you thinking of?
Can you provide an example(s)?

**Comment by TomaszWaszczyk** [comment]
Within 24h I paste here link to examples.

**Comment by TomaszWaszczyk** [comment]
I paste `gif` recording from Storybook. Just an example.

components

**Comment by yangwao** [comment]
Yes, building w/ @kodadot could be easier here. We are recreating original apps, find out more at https://kodadot.js.org

However, we would need some funding too to keep up the pace of ever-growing Substrate 💗

**Comment by siman** [comment]
Thank you for your support @Web3Foundation

**Pull request merged**
