### PR TITLE
Polkadot Swift Grant Application

### PR DESCRIPTION
**Pull request by 2075**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

Swift API for Substrate / Polkadot allows to interact with Substrate nodes, the same way you can do with PolkadotJS, but native for macOS, iOS, watchOS, tvOS, without the burden of crazy toolchains, like react-native etc.

* Port of relevant libraries provided in PolkadotJS
* Demonstration code, example projects

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @2075  What’s the status of this application. Would you still be interested to work on it?

**Comment by 2075** [comment]
Hi @Noc2 Yes, we are working on it as part of zero.io and gamedao.co to create a proper end to end experience for developers (and users). As outlined, there are a variety of issues in terms of existing toolchains. Our assessment of a possible reuse of rust scale-codec via FFI did not lead to a result yet, which would increase development effort to be made, therefore there is no complete timeline yet. Another limitation was certain information regarding fund estimation. Long story short: We can finalise input this week if there is a real interest in this. We see it obv. as a big upside for the ecosystem, but to do it proper it will require extra effort.

**Comment by Noc2** [comment]
@2075 Once you are ready, maybe you can resubmit the application via the google form, so that we can discuss it again during the next meeting.

**Comment by 2075** [comment]
sure. what happened to the old google form?

**Comment by Noc2** [comment]
We switched to a new google sheet since you originally submitted the application.

**Comment by 2075** [comment]
@Noc2  hey David, we have updated the form.

**Comment by 2075** [comment]
hey @Noc2, is there any further information needed at the moment?

**Comment by Noc2** [comment]
Hi @2075 . Thanks again for your grant application and all the effort you put into this. I’m sorry to tell you that the grants committee decided today not to go ahead with your grant application. To be honest, the main reason for this was that we received a similar grant application by another team at a lower price, because of this the grants committee decided to initially go ahead with the other team.

**Comment by Noc2** [comment]
Feel free to apply for another grant at any time.

**Comment by 2075** [comment]
this is already the second (reasonable) grant application, it would have been nice to get some additional information on the current status.

**Comment by Lederstrumpf** [comment]
Hi @2075, I'm sorry about the disappointing outcome. For additional information on the decision:

We understand your cost based on what you were proposing (porting to Swift), but given the maturity of the SCALE libraries and other dependencies, we prefer having FFI bindings rather than a port. We believe the maturity benefits here outweigh having native bindings.
Likewise, there are aspects of your proposal that fall outside of our funding target, like `milestone 1: Identify dependencies and packages from PolkadotJS ecosystem`, which is something that, in our view, is part of the research that goes into crafting a proposal.

I hope this sheds some light on factors that were relevant to our decision.

**Comment by 2075** [comment]
👍

**Pull request closed without merging**
