### PR TITLE
add nsure.network grant

### PR DESCRIPTION
**Pull request by leafan**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract
Nsure is an open insurance platform for Open Finance. The project borrows the idea of Lloyd’s London, a market place to trade insurance risks, where premiums are determined by a Dynamic Pricing Model. Capital mining will be implemented to secure capital required to back the risks at any point of time. A 3-phase crowd voting mechanism is used to ensure every claim is handled professionally.

The project here is a branch for Polkadot, the original ethereum version which is published here: https://github.com/nsure-tech/

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Review by mmagician — CHANGES_REQUESTED** [review]
@leafan Thanks for the application. In order to consider your grant for review, we would need to see more details for the milestones, e.g.:
`Mvp will support capital mining, trading and staking functions which is the same function with ethereum.`
Therefore, for each of: capital mining; trading; staking, please go in-depth of what is expected to be covered by the functionality.

Similarly for M2 & M3, your deliverables are superficial.

Thanks

**Comment by leafan** [comment]
> @leafan Thanks for the application. In order to consider your grant for review, we would need to see more details for the milestones, e.g.:
> `Mvp will support capital mining, trading and staking functions which is the same function with ethereum.`
> Therefore, for each of: capital mining; trading; staking, please go in-depth of what is expected to be covered by the functionality.
> 
> Similarly for M2 & M3, your deliverables are too superficial.
> 
> Thanks

hi, thank you very much for the suggestions

I had added the milestone details for mvp and stage 2, for stage 3 is the official version and dao support for nsure, so it's a little simple. Please check the grant again, thanks.

**Comment by mmagician** [comment]
@leafan

M1: 
1. Can you go into detail of what exactly you mean by capital mining?
Does this mean users are staking tokens (DOTs?) in exchange for nsure tokens? 

2. How do you plan to integrate stable coins? At the moment there are no functional stablecoin bridges with Polkadot.

3. 
> MCR will be locked accordingly when a policy is sold

Who creates and sells the policy? How do you envision policy creation?

4. 
> Staking: Staking rules will be supported to accelerate capital mining.

What rules do you mean? How does that differ from my first question?

M2: 

5. Can you explain the rounds of "3-phase vote claim assessment" & how a user can participate in assessment?

General:
The contracts module is not included by default in the main Polkadot network. Are you going to insure against contracts deployed only in your parachain (that limits the usefulness substantially).

Please be more specific. Milestone deliverables are envisioned to serve as a complete specification of the grant and it will be difficult to later assess the completion of your milestones if they are "Nsure Beta will include new UI/front end/ backend/smart contract". Please provide mockups for `new UI`. We won't be able to proceed unless you are concrete about your project's scope. This applies to all milestones.

**Comment by leafan** [comment]
@mmagician 
hi, i had add some questions at the end of the grant, and also put it here:


* Q1:Can you go into detail of what exactly you mean by capital mining?
Does this mean users are staking tokens (DOTs?) in exchange for nsure tokens?
A1: In regards to capital mining, it is intended to have capital deployed to the pool for MCR requirements. Rewards in order to incentivise capital providers are paid out in Nsure (mined @ 2/block rate). On Ethereum we allow capital to be defined as ETH and stablecoins such as DAI, USDC. In order to be able to adapt to other potential chains, it would be possible to adapt such, i.e. having DOT & other stable coins accepted as capital provision for the capital pool.
 
* Q2: How do you plan to integrate stable coins? At the moment there are no functional stablecoin bridges with Polkadot.
A2: Stablecoins are intended to give users an alternative currency according to their desire for exposure towards market fluctuations. We would rely on each chain’s available ressources/alternatives for such integrations. Nsure can be seen as being focused on functioning as part of the application layer, hence reliability on the given choices of each ecosystem. If at this stage Polkadot has no stablecoin solutions deployed, DOT can be the main resource utilised as means of payment of premiums, settlement, capital provision and claim payouts.
 
* Q3: MCR will be locked accordingly when a policy is sold
Who creates and sells the policy? How do you envision policy creation?
A3: Policy could be bought as long as 1) buyers are comfortable about the price offered by the dynamic pricing model 2)  the MCR is lower than the total funds in Surplus Pool and Capital Pool. Policy is offered by the system, and the pricing is determined by tokens staking on that project.
 
* Q4: Staking: Staking rules will be supported to accelerate capital mining.
What rules do you mean? How does that differ from my first question?
 A4: Nsure tokens can be used to stake on the risks that Nsure token holders feel comfortable with. Insurance premiums are paid daily, and Nsure token holders benefit from the system and leverage provided. Staking needs study on the risk of projects, which have higher return and higher risk accordingly. Capital Mining provides the additional funds to support business development, it is the second cushion of the potential claims, which have lower risk, and the return determined by how much funds are in capital mining.

* Q5: Can you explain the rounds of "3-phase vote claim assessment" & how a user can participate in assessment?
A5: Phase 1, all policyholders vote whether to file the claims or not, which is designed to prevent the waste of auditing and public voting resource from malicious claim requests. Phase 2, professional auditing companies vote whether the claim should be paid, we believe claim assessments are highly complex and require domain specific knowledge. Phase 3, Public vote, if phase 2 is challenged, where users can participate and share the reward.For more details, please reach thewhite paper.


and for the general section, we maybe deploy it in the solidty-supported parachain such as moonbean first(may have to wait for their mainnet~~). for our point for insurance is very import for smart contracts secruity and i think polkadot ecosystem also need an insurance project for smart contracts. And for the project details, you can checkout our whitepaper here: https://nsure.network/Nsure_WP_0.7.pdf

And for the mocks or UI, actually our engineers are working for it, and may run out about 1-2 weeks later, and will post or send it to you. It may fully different with the mvp, and the logic or steps may have much same with it.

Thanks.

**Pull request merged**
