### PR TITLE
grant application for the governance OS (Nuclei Studio OÜ)

### PR DESCRIPTION
**Pull request by ETeissonniere**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract

> This project could be a part of the `Public Voting System - Open Government and E-Participation Web Software` section on the Polakdot Stack.

This project covers the development of governance / organizations focused pallets. One of the use cases for it could be to manage cities or public structures in an open manner which is why I think it could be linked to the Open Government section of the stack.

I hope to be able to take this further via a complete suite / dashboard after this grant.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by dvc94ch** [comment]
> sunshine is building some modules for this too, however they also seems to be limited to a parachain's governance model.

We welcome other entrances in this space. However as a the cto of sunshine I'm curious as to what you mean exactly

**Comment by ETeissonniere** [comment]
Hey @dvc94ch sure no problems! What I meant is that existing modules such as the ones from parity or sunshine seems to still be limited to coding a governance model inside a runtime (this is what I meant in the text you are quoting). This means that the developers of a parachain can create their own model and system with ease straight from the runtime code. However, I didn't see other projects focusing on letting the users of a chain create their own organizations. I am basically trying to focus on another layer of the stack if it makes sense? Unless I am mistaken or overlooked something?

**Comment by dvc94ch** [comment]
We support an arbitrary number of orgs if that's what you're referring to, that's why I was a little confused

**Comment by ETeissonniere** [comment]
Got it! I wasn't aware of this so this is good to know :). I do want to end up with the tools required to build a DAO chain indeed. Maybe I should also have a deeper look into your own project, I am sure there could be some potential synergies at some point in time.

**Pull request merged**
