### PR TITLE
Clarifying use of the badge

### PR DESCRIPTION
**Pull request by semuelle**
- Removing unnecessary newlines
- stricter language
- more structure (taken from email template)

Do we need someone from legal to review this?

### CODE REVIEW

**Comment by Noc2** [comment]
@semuelle the "Foundation." at the end is probably wrong. Otherwise it looks good.

**Comment by semuelle** [comment]
Yep, thanks.

**Comment by Noc2** [comment]
I also quickly fixed the additional sentence at the end: https://github.com/w3f/General-Grants-Program/commit/8a23ef68c7512fa0d437554640601ef28cea3fca

**Comment by semuelle** [comment]
yeesh, thanks for noticing.

**Pull request merged**
